name: open-chat-app
  
services:
  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    restart: always
    networks:
      - open-chat-net

  api:
    image: api
    build:
      context: ./api
      dockerfile: ../docker/api.Dockerfile
    container_name: api
    networks:
      - open-chat-net
    env_file:
      - ./api/.env
    depends_on:
      - redis
    restart: on-failure:10
    
  web:
    image: web
    build:
      context: ./web
      dockerfile: ../docker/web.Dockerfile
    container_name: web
    networks:
      - open-chat-net
    depends_on:
      - api
      - redis
    restart: on-failure:10
  
  nginx:
    image: nginx-server
    build:
      context: ./nginx
      dockerfile: ../docker/nginx.Dockerfile
    container_name: nginx
    networks:
      - open-chat-net
    ports:
      - 80:80
    depends_on:
      - api
      - web
    restart: on-failure:5

networks:
  open-chat-net:
    driver: bridge