MONGODB_DATABASE_NAME = "chat_app"
MONGODB_TEST_DATABASE_NAME = "test_database"
MONGODB_DEFAULT_URL = "mongodb://localhost:27017"

IN_PRODUCTION = False
TESTING = True

# In second
TOKEN_EXPIRATION_TIME = 3600
TOKEN_ALGORITHM = "HS256"
