name: Deploy chat app
run-name: Deploying to AWS EC2 🚀
on:
  push:
      branches:
        - master
  
jobs:
  deploy_on_aws:
    name: Deploy on aws ec2 instance
    runs-on: ubuntu-24.04
    steps:
      - name: Set up ssh
        run: |
          sudo apt update -y 
          
          sudo apt upgrade -y

          sudo apt install ssh

          sudo systemctl start ssh
          
          sudo systemctl enable ssh
          
          sudo ufw allow ssh && sudo ufw enable

      - name: Login to the ec2 using ssh, rebuild images, run containers
        run: |
          ssh -i {{ secrets.openchat_ec2_key }} {{ secrets.ec2_username }}@{{ secrets.ec2_domaine }}

          cd web-chat-app

          docker compose down

          docker system prune -af

          cd ..

          rm -rf web-chat-app

          git clone https://github.com/Romulad/web-chat-app

          cat env-file > web-chat-app/api/.env

          cd web-chat-app

          docker compose up -d

